#### Network ####
#Due to the null model, the network generated by this script 
#is slightly different from the network in the paper.
rm(list = ls())
require(igraph)
require(tidyverse)
otutb.name <- list.files("network_otu//", pattern = '.csv')

Net_Infer <- function(p.mat.corr = p.mat.corr, 
                      p.mat.jac = p.mat.jac,
                      cor.mat = cor.mat, 
                      jac.mat = jac.mat,
                      otu.tb = otu.tb,
                      graph.name = graph.name,
                      p.adjust.methods,
                      cor.threshold = cor.threshold,
                      jac.threshold = jac.threshold
){
  # p merge
  q = -2*log(p.mat.corr)-2*log(p.mat.jac)
  p.mat <- matrix(nrow = dim(p.mat.corr)[1],ncol = dim(p.mat.corr)[1])
  for(j in 1:dim(p.mat.corr)[1]){
    for(k in 1:dim(p.mat.corr)[1]){
      p.mat[j,k] <- pchisq(q[j,k],4,lower.tail = FALSE)
    }}
  # p adjust
  p.adj <- matrix(p.adjust(p.mat,p.adjust.methods),nrow = dim(p.mat))
  diag(p.adj) <- 1
  # correlation matrix
  adj.mat <- matrix(nrow = dim(p.mat)[1],ncol = dim(p.mat)[1])
  adj.mat[] <- 1
  adj.mat[p.mat>0.05] <- 0
  adj.mat[abs(cor.mat) < cor.threshold] <- 0
  adj.mat[abs(jac.mat) < jac.threshold] <- 0
  g.adj <- graph_from_adjacency_matrix(adj.mat,weighted = T,diag = FALSE,mode = "undirected")
  # annotation the nodes information with OTU number
  V(g.adj)$name <- colnames(otu.tb)
  E(g.adj)$dir <- cor(otu.tb, method = "spearman")[lower.tri(adj.mat)][adj.mat[lower.tri(adj.mat)]==1]
  # remove isolated nodes
  g.adj <- V(g.adj)[igraph::degree(g.adj) == 0] %>%  igraph::delete.vertices(g.adj,.)
  write.graph(g.adj,
              file = paste("network_graph/", 
                           graph.name,
                           sep = ""),
              format = "graphml")
}

# RMT
# require(RMThreshold)

# cor.mat = read.csv(paste("network_otu/boot_mean/sp_",otutb.name,sep=""),header = TRUE, row.names = 1)
# rm.get.threshold(as.matrix(cor.mat),interactive = F,discard.zeros = T,discard.outliers = F,interval = c(0.2,0.95),plot.comp=F)

#The Spearman threshold of the six site-level bacterial networks was around 0.8.
cor.threshold.list <- c(0.8)
#The jac threshold of the six site-level bacterial networks 
#was setted to be 0.2 following Berry and Widder 2014.
jac.threshold.list <- c(0.2)

  Net_Infer(p.mat.corr = read.csv(paste("network_otu/pmat/sp_",otutb.name,sep=""),
                                  header = TRUE,row.names = 1), 
            p.mat.jac = read.csv(paste("network_otu/pmat/jac_",otutb.name,sep=""),
                                 header = TRUE,row.names = 1),
            cor.mat = read.csv(paste("network_otu/boot_mean/sp_",otutb.name,sep=""),
                               header = TRUE, row.names = 1), 
            jac.mat =  read.csv(paste("network_otu/boot_mean/jac_",otutb.name,sep=""),
                                header = TRUE, row.names = 1),
            otu.tb = read.csv(paste("network_otu/",otutb.name,sep=""),
                              header = TRUE,row.names = 1) %>% t(),
            p.adjust.methods='fdr',
            cor.threshold = cor.threshold.list,
            jac.threshold = jac.threshold.list,
            graph.name = gsub("csv","graphml",otutb.name)
  )
  